### ISSUE TITLE
Is there any code for the presentations?

### ISSUE THREAD

**Issue by MrYossu** [jbogard/presentations#30]
Just came across a talk you gave at NDC ([video here](https://vimeo.com/131633177)), and would really like to see the full solution.

I looked through your repos, but couldn't find one that matched.

Is the code form that presentation available?

Thanks

**Comment by jbogard** [comment]
https://github.com/jbogard/ContosoUniversityDotNetCore-Pages

Thanks!

**Comment by MrYossu** [comment]
@jbogard Thanks. I already looked at that one, but the structure doesn't look like the code you showed in the talk. I was expecting a Features folder, with all the code for each feature below it. I know you have the `Pages` folder, with a subfolder for each feature, but that's pretty standard. I was expecting something different.

Thanks again.

**Comment by jbogard** [comment]
This is the one then: https://github.com/jbogard/ContosoUniversityDotNetCore but with Razor Pages it supports feature folders out-of-the-box. Just not called "Features" but that's fine.

**Comment by MrYossu** [comment]
@jbogard Thanks
